spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?useSSL=true&autoConnected=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&
    username: root
    password: 123456
#redis集群
  redis:
    #host: 127.0.0.1
    #port: 6379
    timeout: 20000
#    集群环境打开下面注释，单机不需要打开
    cluster:
#      集群信息
      nodes: idyll.life:8001,idyll.life:8002,idyll.life:8003,idyll.life:8004,idyll.life:8005,idyll.life:8006
      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#      maxRedirects: 3
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: redis123

server:
  port: 18080
  context-path: /springboot 
  devtools:
    restart:
      enabled: true


#    password: hehuiredis177
    
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations:
#- classpath:mybatis/mapper/*.xml
  
debug: false
